version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    image: phelype/app
    depends_on:
      - db
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    image: phelype/nginx
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    container_name: mydb
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'nodedb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./app/assets/sql:/docker-entrypoint-initdb.d

volumes:
  my-db:
